### ISSUE TITLE
Checking for undefined doesn't work

### ISSUE THREAD

**Issue by Haroenv** [KittyGiraudel/map-dater#5]
Seems like although you are asking `typeof`, it still matters if it's undefined.

```
/Users/haroenv/git/test/map-dater/src/helpers/translate.js:11
      typeof dictionary[key] === 'undefined'
             ^

ReferenceError: dictionary is not defined
    at /Users/haroenv/git/test/map-dater/src/helpers/translate.js:11:14
    at choices.map (/Users/haroenv/git/test/map-dater/src/helpers/spec.js:18:11)
    at Array.map (native)
    at getChoices (/Users/haroenv/git/test/map-dater/src/helpers/spec.js:16:11)
    at specifications.map (/Users/haroenv/git/test/map-dater/src/helpers/spec.js:23:12)
    at Array.map (native)
    at Object.<anonymous> (/Users/haroenv/git/test/map-dater/src/helpers/spec.js:22:35)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
```

**Comment by KittyGiraudel** [comment]
Wait, that comes from the fact that the dictionary is not being found. Do you see any other log/error right before this one? Probably is a path issue at this point.

**Comment by KittyGiraudel** [comment]
Maybe this helps: https://github.com/HugoGiraudel/map-dater/commit/fa2ccc33356ba6aac750344e23dfee6341510098?

**Comment by Haroenv** [comment]
[this](https://gist.github.com/Haroenv/1b682018d1b2abdf6bed2269e5e76f30) is the full `npm-debug.log` when doing `npm start`. When just doing `map-dater` no other errors are found

**Comment by KittyGiraudel** [comment]
Okay this seems to come from Node 6. I can reproduce in Node 6, not in Node 5. I'll check.

**Comment by Haroenv** [comment]
That change didn't give any different errors

**Comment by KittyGiraudel** [comment]
Maybe this: https://github.com/HugoGiraudel/map-dater/commit/f3ee9c0e247bb4385a866ea045d19fc00653d387?

**Comment by Haroenv** [comment]
yes! this is fixed now
